import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'package:aahar_ai/data/local/entities/food_log.dart';
import 'package:aahar_ai/data/local/entities/user_profile.dart';

class PdfService {
  
  static Future<void> generateProfessionalReport(List<FoodLog> logs, UserProfile profile) async {
    final pdf = pw.Document();
    
    // Sort logs (Newest first)
    logs.sort((a, b) => b.timestamp.compareTo(a.timestamp));

    // --- CALCULATE AVERAGES ---
    double avgCal = 0, avgProt = 0, avgSugar = 0, avgSodium = 0;
    
    if (logs.isNotEmpty) {
      for (var log in logs) {
        avgCal += log.totalCalories.isFinite ? log.totalCalories : 0;
        avgProt += log.totalProtein.isFinite ? log.totalProtein : 0;
        avgSugar += log.sugar.isFinite ? log.sugar : 0;
        avgSodium += log.sodium.isFinite ? log.sodium : 0;
      }
      avgCal /= logs.length;
      avgProt /= logs.length;
      avgSugar /= logs.length;
      avgSodium /= logs.length;
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        
        footer: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,
            margin: const pw.EdgeInsets.only(top: 20),
            child: pw.Text(
              'Generated by Aahar AI • Page ${context.pageNumber} of ${context.pagesCount}\nNot for medical diagnosis. Consult a doctor.',
              textAlign: pw.TextAlign.right,
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
            ),
          );
        },

        build: (pw.Context context) {
          return [
            // 1. HEADER
            _buildReportHeader(),
            pw.SizedBox(height: 20),

            // 2. PATIENT INFO (UPDATED)
            _buildPatientInfoTable(profile),
            pw.SizedBox(height: 30),

            // 3. RISK ANALYSIS
            pw.Text("NUTRITIONAL RISK ANALYSIS", style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, letterSpacing: 1, color: PdfColors.blueGrey800)),
            pw.Divider(color: PdfColors.grey400),
            _buildMicroNutrientSummary(avgSugar, avgSodium, profile),
            pw.SizedBox(height: 30),

            // 4. LOGS
            pw.Text("DIETARY LOGS", style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, letterSpacing: 1, color: PdfColors.blueGrey800)),
            pw.Divider(color: PdfColors.grey400),
            _buildDetailedLogTable(logs),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Medical_Report_${profile.name.replaceAll(' ', '_')}',
    );
  }

  // --- SAFE NUMBER HELPER ---
  static String _safeVal(double value, [String suffix = '']) {
    if (value.isNaN || value.isInfinite) return '0$suffix';
    return '${value.round()}$suffix';
  }

  // --- WIDGETS ---

  static pw.Widget _buildReportHeader() {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('AAHAR AI HEALTH', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.green800)),
            pw.Text('Personalized Nutrition Report', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
          ],
        ),
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
          decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey300), borderRadius: pw.BorderRadius.circular(4)),
          child: pw.Text('DATE: ${DateFormat('yyyy-MM-dd').format(DateTime.now())}', style: const pw.TextStyle(fontSize: 10)),
        ),
      ],
    );
  }

  static pw.Widget _buildPatientInfoTable(UserProfile profile) {
    // FIX: Join all conditions with a comma, or show "None"
    String conditionsString = profile.healthConditions.isNotEmpty 
        ? profile.healthConditions.join(', ') 
        : "None";

    return pw.Container(
      decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey300), borderRadius: pw.BorderRadius.circular(4)),
      child: pw.Column(
        children: [
          pw.Container(
            width: double.infinity,
            color: PdfColors.grey100,
            padding: const pw.EdgeInsets.all(6),
            child: pw.Text("PATIENT PROFILE", style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
          ),
          pw.Padding(
            padding: const pw.EdgeInsets.all(10),
            child: pw.Column(
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    _buildInfoColumn("Name", profile.name),
                    _buildInfoColumn("Age / Sex", "${profile.age} / ${profile.gender}"),
                    _buildInfoColumn("Height", "${profile.height} cm"),
                    _buildInfoColumn("Weight", "${profile.currentWeight} kg"),
                    _buildInfoColumn("BMI", "${profile.bmi.toStringAsFixed(1)}"),
                  ],
                ),
                pw.SizedBox(height: 10),
                pw.Divider(color: PdfColors.grey200),
                pw.SizedBox(height: 10),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    _buildInfoColumn("Activity Level", profile.activityLevel),
                    _buildInfoColumn("Goal", profile.goal),
                    // EXPANDED CONDITION COLUMN
                    pw.Expanded(
                      child: pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.end,
                        children: [
                          pw.Text("CONDITIONS", style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
                          pw.SizedBox(height: 2),
                          pw.Text(conditionsString, style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.red900)),
                        ],
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildInfoColumn(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label.toUpperCase(), style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
        pw.SizedBox(height: 2),
        pw.Text(value, style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
      ],
    );
  }

  static pw.Widget _buildMicroNutrientSummary(double avgSugar, double avgSodium, UserProfile profile) {
    final safeSugar = avgSugar.isFinite ? avgSugar : 0.0;
    final safeSodium = avgSodium.isFinite ? avgSodium : 0.0;

    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        _buildRiskCard("Avg Sugar Intake", "${safeSugar.toStringAsFixed(1)}g", safeSugar > 30, "Max recommended: 30g"),
        _buildRiskCard("Avg Sodium Intake", "${safeSodium.toStringAsFixed(0)}mg", safeSodium > 2300, "Max recommended: 2300mg"),
        _buildRiskCard("Daily Calorie Avg", "${profile.dailyCalorieGoal.toInt()}", false, "Target Goal"),
      ],
    );
  }

  static pw.Widget _buildRiskCard(String title, String value, bool isHigh, String subtext) {
    return pw.Container(
      width: 150,
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: isHigh ? PdfColors.red200 : PdfColors.green200),
        borderRadius: pw.BorderRadius.circular(4),
        color: isHigh ? PdfColors.red50 : PdfColors.green50,
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700)),
          pw.SizedBox(height: 4),
          pw.Text(value, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: isHigh ? PdfColors.red800 : PdfColors.green800)),
          pw.SizedBox(height: 4),
          pw.Text(subtext, style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
        ],
      ),
    );
  }

  static pw.Widget _buildDetailedLogTable(List<FoodLog> logs) {
    return pw.TableHelper.fromTextArray(
      headers: ['Time', 'Food Item', 'Cals', 'Protein', 'Sugar', 'Sodium'],
      data: logs.map((log) {
        return [
          DateFormat('MMM d, HH:mm').format(log.timestamp),
          log.foodName,
          _safeVal(log.totalCalories),  
          _safeVal(log.totalProtein, 'g'), 
          _safeVal(log.sugar, 'g'),     
          _safeVal(log.sodium, 'mg'),   
        ];
      }).toList(),
      border: null,
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9, color: PdfColors.white),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey700),
      cellStyle: const pw.TextStyle(fontSize: 9),
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.centerLeft,
        2: pw.Alignment.centerRight,
        3: pw.Alignment.centerRight,
        4: pw.Alignment.centerRight,
        5: pw.Alignment.centerRight,
      },
      oddRowDecoration: const pw.BoxDecoration(color: PdfColors.grey100),
    );
  }
}